routes/web.php
<?php


use Illuminate\Http\Request;
use App\Http\Controllers\Auth\LoginController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);//Включение подтверждения по электронной почте
Route::get('/verify/{token}', 'Auth\RegisterController@verify')->name('register.verify');

Auth::routes();
Route::get('auth/{provider}', [ LoginController::class, 'redirectToProvider' ]);
Route::get('auth/{provider}/callback', [ LoginController::class, 'handleProviderCallBack' ]);

Route::put('{id}/change-password', 'Auth\ChangePasswordController@changePassword')->name('pass');

Route::get('password/changepassword', function () {
    return view('auth.passwords.changepassword', ['name' => Auth::user()->name]);
});

Route::get('/', function () {
    return view('welcome');
});

Route::group(['namespace' => 'Web', 'as' => 'web.'], function () {

    Route::group(['namespace' => 'Category', 'as' => 'category.'], function () {
        Route::get('category/', 'CategoryController@index')->name('index');
    });
    Route::get('switch-lang/{langCode}', 'LocaleController@setLang')->name('set.lang') ;
    Route::get('send-email/{message}', 'LocaleController@contactMe')->name('send.email') ;
});

//Route::get('switch-lang/{langCode}', 'App\Http\Controllers\Web\LocaleController@setLang')->name('set.lang') ;

//Route::get('/categories', function () {
//    $categories = \App\Category::all();
//    return view('categories', compact('categories'));
//});


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/feedback', 'FeedbackController@index')->name('feedback.index');
Route::post('/feedback', 'FeedbackController@send')->name('feedback.send');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-dark bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- ФЛАГИ ТУТ -->
            <div class="switch-lang">
                <a href="{{route('web.set.lang', ['langCode' => 'ru']) }}">
                    <img width="32" src="https://www.ph4.ru/DL/ICO/flags/classic_go-flat_64/ru.png"
                         alt="">
                </a>
                <a href="{{route('web.set.lang', ['langCode' => 'en']) }}">
                    <img width="32" src="https://www.ph4.ru/DL/ICO/flags/classic_go-flat_64/uk.png"
                         alt="">
                </a>
            </div>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('layouts.login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('layouts.register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('layouts.logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>
</body>
</html>